name: Auto deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 15

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run docs:build

      - uses: benjlevesque/short-sha@v1.2
        id: short-sha

      - name: Publish
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          allow_empty_commit: false
          build_dir: docs/.vuepress/dist
          commit_message: "Auto deploy for commit ${{ steps.short-sha.outputs.sha }}"
          fqdn: ysnotes.omico.me
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
